# fly.toml file generated for ddr-discord-bot on 2022-12-06T16:45:28Z

app = "ddr-discord-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
TITAN_BOT_HTTP_LISTEN_INTERFACES="None"

[[services]]
    http_checks = []
    internal_port = 8080
    protocol = "tcp"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

